# Generated by Django 2.1a1 on 2018-06-17 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 17, 15, 59, 29, 646040, tzinfo=utc)),
        ),
    ]
